SELECT
?domain ?domainLabel ?InterPro_ID
WHERE {

    VALUES ?protein { wd:{{protein_qid}}  } .    

    ?protein wdt:P527 ?domain . 

    ?domain wdt:P2926 ?InterPro_ID .
  
    ?domain rdfs:label ?domainLabel .
    FILTER (LANG (?domainLabel) = "en")  
}

