SELECT
?complex ?complexLabel ?Complex_Portal_acession_ID
WHERE {

    VALUES ?protein { wd:{{protein_qid}}  } .    

    ?complex wdt:P527 ?protein . 

    ?complex wdt:P7718 ?Complex_Portal_acession_ID .
  
    ?complex rdfs:label ?complexLabel .
    FILTER (LANG (?complexLabel) = "en")   
}

